### ISSUE TITLE
[Bug]: Listen Now — Missing `tagline` for tall cards

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Fujisan-BugTracker#33]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://cider.sh/legal/conduct) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/ciderapp/Fujisan-BugTracker/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs) and none solved my issue. (* These are outdated and may not necessarily be possible in the current app version. *)

### What operating system are you using?

Windows (Only Supported)

### Operating System Version

Windows 10 22H2 (19045.2604)

### Describe the Bug

The tagline/subtitle for tall recommendation cards are missing.

### Steps to Reproduce

1. Open Listen Now
2. The subtitle text is missing in both the top carousel and the "Go to the site" card for Replay

### Anything else?

![image](https://user-images.githubusercontent.com/32032824/223414730-4d97e53e-ec53-442a-9c39-0b8fba2f9653.png)
*Apple Music Web Player: Top recommendation cards*

![image](https://user-images.githubusercontent.com/32032824/223414966-a6a9194d-b6da-4c40-95a8-c02a7026a1e3.png)
*Apple Music Web Player: Replay cards*

**Comment by Swiftzerr** [comment]
Looking into this now

**Comment by Swiftzerr** [comment]
Fixed in latest commit

**Comment by SoNothingMC** [comment]
This is an extreme nitpick at this point... however, the Replay card still does not have taglines yet as of the current Sabiiro build.

Build https://discord.com/channels/843954443845238864/905459703092490340/1087210306331222097

**Comment by Swiftzerr** [comment]
Added that too
